title: All about AI AND CLOUD
author: Jainshashank7125
email: shashankjain.cse19@ggct.co.in
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello everyone I am starting this blog to share my thoughts about the new innovations in the field of Artificial Intelligence and Cloud Services.
  Hope to see a good response from your side.

# social links
twitter_username: Jainshashank7 # DO NOT include the @ character, or else the build will fail!
github_username:  Jainshashank7125 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
